In [1]:
import numpy as np 

In [2]:
# Create a numpy array 
A = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(A)

[1 2 3 4 5 6 7 8 9]


In [3]:
# Create a numpy array with strings 
S = np.array(["Jim", "Tim", "Mim"])
print(S)

['Jim' 'Tim' 'Mim']


In [4]:
# Check the data type of `A`
A.dtype

dtype('int64')

In [5]:
# Check rthe data type of `S`
S.dtype

dtype('<U3')

In [6]:
# Create an array of integers 
B = np.array([1, 2, 3, 4, 5], dtype='int')
print(B)

[1 2 3 4 5]


In [7]:
# Check data type of `B`
B.dtype

dtype('int64')

In [8]:
# Create an array of floats 
C = np.array([1, 2, 3, 4, 5], dtype='float32')
print(C)

[1. 2. 3. 4. 5.]


In [9]:
# Check the data type of `C`
C.dtype

dtype('float32')

In [10]:
# Check byte size of `A`
A.nbytes

72

In [11]:
# Check byte size of `S`
S.nbytes

36

In [12]:
# Check byte size of `B`
B.nbytes

40

In [13]:
# Check byte size of `C`
C.nbytes

20

In [14]:
# Create an array of floats 
arr = np.array([1, 2, 3, 4, 5], dtype='float32')
print(arr)

[1. 2. 3. 4. 5.]


In [15]:
# Convert the array into integer using astype()
arr.astype('int')

array([1, 2, 3, 4, 5])

In [16]:
# Now check the data type again 
arr.dtype

dtype('float32')