In [1]:
# import numpy
import numpy as np 

In [2]:
A = np.arange(0, 16).reshape(4,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [3]:
# determinant of A 
np.linalg.det(A) 

0.0

In [4]:
B = np.matrix("4,5,6,7;2,-3,3,3; 3,4,5,6; 4, 7,8,9")

In [5]:
# determinant of B 
np.linalg.det(B)

12.000000000000032

In [6]:
# rank 
np.linalg.matrix_rank(A)

2